server:
  port: 8004
  context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saka?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 112358
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   hibernate:
     ddl-auto: update
#  mail:
#    host: smtp.126.com
#    username: rangaofei085@126.com
#    password: rangaofei123
#    default-encoding: UTF-8
  data:
    jpa:
      repositories:
        enabled: true
  logging:
    level:
      org.springframework:
        data: DEBUG
        security: DEBUG
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "

  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"


springfox.documentation.swagger.v2.path: /auth/api-docs
#springfox.documentation.swagger.v2.host=test
custom:
  resourceLocationProtocol: file://
  resourceLocation: /usr/local/upload/
  tmpLocation: /usr/local/upload/tmp/