server:
  port: 8004
  context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saka?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 112358
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   hibernate:
     ddl-auto: update

  data:
    jpa:
      repositories:
        enabled: true
#  logging:
#    level:
#      org.springframework:
#        data: DEBUG
#        security: DEBUG

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "

  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"
