server:
  port: 8004
  context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saka?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 112358
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   hibernate:
     ddl-auto: update


  data:
    jpa:
      repositories:
        enabled: true


jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "

  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"
logging:
  level: debug
#logging:
#  pattern:
#    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
