#%RAML 1.0
title: 教师助手2.0-API
version: 1

baseUri: http://192.168.1.161:8004/api
documentation:
  - title: TeacherAssistant2.0
    content: |
      教师助手的接口文档，当前处于测试阶段，随时改正
 

  
/auth/student:
  description: 用于登陆注册和刷新token
  /register: # optional resource
    description: for student register
    post:
      body:
        application/json:
          type: |
            {
              "name": String,
              "phone": String,
              "password": String
            }
          example: |
            {
              "name": "mary",
              "phone": "123456",
              "password": "jkli"
            }
      responses: # declare a response
        201: # HTTP status code
          body:
            application/json:
              type: | # structural definition of a response (schema or type)
                {
                  "code": int,
                  "message": String,
                  "body":{
                    "student":{
                      "studentId": String,
                      "name": String,
                      "password": String,
                      "phone": String,
                      "crteatedTime": DatSTringe
                    },
                    "token":{
                      "accessToken": String,
                      "refreshToken": String
                    }
                  }
                }
              example: |
                {
                  "code": 201,
                  "message": "success",
                  "body": {
                    "student":{
                      "studentId": "15087254904257",
                      "name": "mary",
                      "password": "qwer",
                      "phone": "123456",
                      "crteatedTime": "1508725490425"
                    },
                    "token":{
                      "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MDg3MjU0OTAsInN1YiI6IlNTUzEyMzQ1NiIsImV4cCI6MTUwOTMzMDI5MH0.Bpb5MM_n37JYH9v0xm9lzlF3-Pod1e_vFqyAkLtnrzc",
                      "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MDg3MjU0OTAsInN1YiI6IlNTUzEyMzQ1NiIsImV4cCI6MTUyNjg2OTQ5MH0.QAQDe8Gpj8J5d_T2LwZrWiiqXHtQI7K_ewTF3seVc2A"
                    }
                  }
                }
  /login:
    description: for student login
    post:
      body:
        application/json:
          type: |
            {
              "phone": String,
              "password": String
            }
          example: |
            {
              "phone": "123",
              "password": "jkli"
            }
      responses: 
        201:
          body: 
            application/json:
              type: |
                {
                  "code": int,
                  "message": String,
                  "body": {
                    "student":{
                      "studentId": String,
                      "name": String,
                      "password": String,
                      "phone": String,
                      "crteatedTime": String
                    },
                    "token": {
                      "accessToken": String,
                      "refreshToken": String
                    }
                  }
                }
              example: |
                {
                  "code": 201,
                  "message": "success",
                  "body": {
                    "student":{
                      "studentId": "15087254904257",
                      "name": "mary",
                      "password": "qwer",
                      "phone": "123456",
                      "crteatedTime": "1508725490000"
                    },
                    "token": {
                      "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MDg3NDY1NTAsInN1YiI6IlNTUzEyMzQ1NiIsImV4cCI6MTUwOTM1MTM1MH0.85_Na-uDpsC20G9O-S12fUdzZaxNTuqVCLKrxiFKd0M",
                      "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MDg3NDY1NTAsInN1YiI6IlNTUzEyMzQ1NiIsImV4cCI6MTUyNjg5MDU1MH0.Y3zRD95cgyQgmyWue_tatdcosNXnCfBvaaFvVTNIIaE"
                    }
                  }
                }
/auth/teacher:
  /register: # optional resource
    description: for student register
    post:
      body:
        application/json:
          type: |
            {
              "name": String,
              "phone": String,
              "password": String
            }
          example: |
            {
              "name": "mary",
              "phone": "123456",
              "password": "jkli"
            }
      responses: # declare a response
        201: # HTTP status code
          body:
            application/json:
              type: | # structural definition of a response (schema or type)
                {
                  "code": int,
                  "message": String,
                  "body":{
                    "teacher":{
                      "teacherId": String,
                      "name": String,
                      "password": String,
                      "phone": String,
                      "crteatedTime": DatSTringe
                    },
                    "token":{
                      "accessToken": String,
                      "refreshToken": String
                    }
                  }
                }
              example: |
                {
                  "code": 201,
                  "message": "success",
                  "body": {
                    "teacher":{
                      "teacherId": "15087254904257",
                      "name": "mary",
                      "password": "qwer",
                      "phone": "123456",
                      "crteatedTime": "1508725490425"
                    },
                    "token":{
                      "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MDg3MjU0OTAsInN1YiI6IlNTUzEyMzQ1NiIsImV4cCI6MTUwOTMzMDI5MH0.Bpb5MM_n37JYH9v0xm9lzlF3-Pod1e_vFqyAkLtnrzc",
                      "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MDg3MjU0OTAsInN1YiI6IlNTUzEyMzQ1NiIsImV4cCI6MTUyNjg2OTQ5MH0.QAQDe8Gpj8J5d_T2LwZrWiiqXHtQI7K_ewTF3seVc2A"
                    }
                  }
                }
  /login:
    description: for student login
    post:
      body:
        application/json:
          type: |
            {
              "phone": String,
              "password": String
            }
          example: |
            {
              "phone": "123",
              "password": "jkli"
            }
      responses: 
        201:
          body: 
            application/json:
              type: |
                {
                  "code": int,
                  "message": String,
                  "body": {
                    "teacher":{
                      "teacherId": String,
                      "name": String,
                      "password": String,
                      "phone": String,
                      "crteatedTime": String
                    },
                    "token": {
                      "accessToken": String,
                      "refreshToken": String
                    }
                  }
                }
              example: |
                {
                  "code": 201,
                  "message": "success",
                  "body": {
                    "teacher":{
                      "teacherId": "15087254904257",
                      "name": "mary",
                      "password": "qwer",
                      "phone": "123456",
                      "crteatedTime": "1508725490000"
                    },
                    "token": {
                      "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MDg3NDY1NTAsInN1YiI6IlNTUzEyMzQ1NiIsImV4cCI6MTUwOTM1MTM1MH0.85_Na-uDpsC20G9O-S12fUdzZaxNTuqVCLKrxiFKd0M",
                      "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1MDg3NDY1NTAsInN1YiI6IlNTUzEyMzQ1NiIsImV4cCI6MTUyNjg5MDU1MH0.Y3zRD95cgyQgmyWue_tatdcosNXnCfBvaaFvVTNIIaE"
                    }
                  }
                }
/student/{student_id}:
  /joinclass:
    description: 加入班级
    post:
      queryParameters:
        class_id:
      responses:
        200:
          body:
            application/json:
              type: |
                {
                  "code": int,
                  "message": String,
                  "body": {
                    "teamId": String,
                    "teamName": String,
                    "teamIntroduction": String,
                  }
                }
              example: |
                {
                  "code": 201,
                  "message": "保存成功",
                  "body": {
                    "teamId": "6611909120",
                    "teamName": "sannianji",
                    "teamIntroduction": "haowan",
                  }
                }
      headers:
        Authorization:
          type: string
          description: access_token验证
          example: |
            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==
  /getclasses:
    get:
      responses:
        200:
          body:
            application/json:
              type: |
                {
                  "code": int,
                  "message": String,
                  "body": [{
                    "teamId": String,
                    "teamName": String,
                    "teamIntroduction": String,
                  },..]
                }
              example: |
                {
                  "code": 201,
                  "message": "成功",
                  "body": [
                    {
                      "teamId": "6611909120",
                      "teamName": "sannianji",
                      "teamIntroduction": "haowan"
                    },
                    {
                      "teamId": "6611841358",
                      "teamName": "ernianji",
                      "teamIntroduction": "haowan"
                    },
                    {
                      "teamId": "6607997579",
                      "teamName": "yinianji",
                      "teamIntroduction": "haowan"
                    }
                  ]
                }
      headers:
        Authorization:
          type: string
          description: access_token验证
          example: |
            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==
  /{class_id}/gethomeworks:
    get:
      responses: 
        200:
          body: 
            application/json:
              type: |
                {
                }
              example: |
                {
                }
      headers:
        Authorization:
          type: string
          description: access_token验证
          example: |
            Authorization: Bearer QWxhZGRpbjpvcGVuIHNlc2FtZQ==
    
  # get:
  #   headers:
  #     Authorization:
  #       type: string
  #       description: Basic authentication header
  #       example: |
  #         Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==
  # put:
  #   body:
  #     application/x-www-form-urlencoded:
  #       properties:
  #         name:
  #           description: name on account
  #           type: string
  #           examples:
  #             example1: Naruto Uzumaki
  #             example2: Kevin Renskers
  #         gender:
  #           enum: ["male", "female"]